# Note that any updates to this files will not be applied in CI
"C:app-wiring":
  - changed-files:
      - any-glob-to-any-file:
          - app/*.go
          - app/params/**
          - app/queries/**
"C:x/tax":
  - changed-files:
      - any-glob-to-any-file:
          - x/tax/**
"C:x/tokenfactory":
  - changed-files:
      - any-glob-to-any-file:
          - x/tokenfactory/**
"C:x/xfeemarket":
  - changed-files:
      - any-glob-to-any-file:
          - x/xfeemarket/**

"T:build":
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - Dockerfile
          - scripts/*
"T:CI":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*.yml
          - .mergify.yml
          - .golangci.yml
"C:CLI":
  - changed-files:
      - any-glob-to-any-file:
          - client/**
          - x/*/client/**
          - x/**/autocli.go
"C:docs":
  - changed-files:
      - any-glob-to-any-file:
          - bug.md
          - issue.md
          - proto-docs.md
          - README.md
          - x/**/*.md
          - x/**/*/*.md
          - tests/**/*.md
          - adr/*.md
