defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=2"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>=1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to release/v1.0.x branch
    conditions:
      - base=main
      - label=A:backport/v1.0.x
    actions:
      backport:
        branches:
          - release/v1.0.x
  - name: backport patches to release/v2.0.x branch
    conditions:
      - base=main
      - label=A:backport/v2.0.x
    actions:
      backport:
        branches:
          - release/v2.0.x
  - name: backport patches to release/v3.0.x branch
    conditions:
      - base=main
      - label=A:backport/v3.0.x
    actions:
      backport:
        branches:
          - release/v3.0.x
  - name: backport patches to release/v4.0.x branch
    conditions:
      - base=main
      - label=A:backport/v4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x
  - name: backport patches to release/v5.0.x branch
    conditions:
      - base=main
      - label=A:backport/v5.0.x
    actions:
      backport:
        branches:
          - release/v5.0.x
  - name: backport patches to release/v6.0.x-provider branch
    conditions:
      - base=main
      - label=A:backport/v6.0.x-provider
    actions:
      backport:
        branches:
          - release/v6.0.x-provider
  - name: backport patches to release/v6.0.x branch
    conditions:
      - base=main
      - label=A:backport/v6.0.x
    actions:
      backport:
        branches:
          - release/v6.0.x