run:
  tests: true
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - durationcheck
    - errcheck
    - errname
    - copyloopvar
    - fatcontext
    - forcetypeassert
    - gci
    - goconst
    - gochecksumtype
    - gocritic
    - gofumpt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    #   - maintidx (this would be nice to re-enable at some point, to help keep complexity at bay)
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - promlinter
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - whitespace
    - unparam
    - revive
    - usestdlibvars
    - zerologlint

linters-settings:
  revive:
    rules:
      - name: function-result-limit
        severity: warning
        disabled: false
        # limits the number of returns to 5
        arguments: [5]

issues:
  # Exclude all *.pb.gw.go files
  exclude-files:
    - ".*\\.pb\\.gw\\.go$"
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1003:" # requires identifiers with "id" to be "ID".
    - linters:
        - stylecheck
      text: "ST1005:" # punctuation in error messages
  max-issues-per-linter: 10000
  max-same-issues: 10000
