// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mantrachain/coinfactory/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the coinfactory module.
type Params struct {
	DenomCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=denom_creation_fee,json=denomCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"denom_creation_fee" yaml:"denom_creation_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_234fd87d41db534f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDenomCreationFee() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.DenomCreationFee
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "mantrachain.coinfactory.v1beta1.Params")
}

func init() {
	proto.RegisterFile("mantrachain/coinfactory/v1beta1/params.proto", fileDescriptor_234fd87d41db534f)
}

var fileDescriptor_234fd87d41db534f = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x31, 0x4e, 0x33, 0x31,
	0x10, 0x85, 0xd7, 0xfa, 0xa5, 0x14, 0xf9, 0x1b, 0x14, 0x51, 0x90, 0x14, 0x5e, 0x94, 0x2a, 0x05,
	0xd8, 0x0a, 0x20, 0x21, 0x51, 0x26, 0x12, 0x15, 0x41, 0x88, 0x92, 0x26, 0x9a, 0x75, 0x9c, 0xc4,
	0x02, 0x7b, 0x22, 0xdb, 0x41, 0xec, 0x2d, 0xa8, 0xe8, 0x69, 0x39, 0x49, 0xca, 0x94, 0x54, 0x01,
	0x65, 0x6f, 0xc0, 0x09, 0xd0, 0x7a, 0x0d, 0x5a, 0x44, 0x41, 0x65, 0x8f, 0xe6, 0xbd, 0x6f, 0x66,
	0x5e, 0xf3, 0x40, 0x83, 0xf1, 0x16, 0xc4, 0x1c, 0x94, 0xe1, 0x02, 0x95, 0x99, 0x82, 0xf0, 0x68,
	0x73, 0x7e, 0xdf, 0xcf, 0xa4, 0x87, 0x3e, 0x5f, 0x80, 0x05, 0xed, 0xd8, 0xc2, 0xa2, 0xc7, 0x56,
	0x5a, 0x53, 0xb3, 0x9a, 0x9a, 0x45, 0x75, 0x67, 0x77, 0x86, 0x33, 0x0c, 0x5a, 0x5e, 0xfe, 0x2a,
	0x5b, 0xe7, 0xf4, 0xaf, 0x21, 0xb0, 0xf4, 0x73, 0xb4, 0xca, 0xe7, 0x23, 0xe9, 0x61, 0x02, 0x1e,
	0xa2, 0xb1, 0x2d, 0xd0, 0x69, 0x74, 0xe3, 0x8a, 0x58, 0x15, 0xb1, 0x45, 0xab, 0x8a, 0x67, 0xe0,
	0xe4, 0x37, 0xa7, 0x64, 0x57, 0xfd, 0xee, 0x33, 0x69, 0x36, 0xae, 0xc2, 0xee, 0xad, 0x27, 0xd2,
	0x6c, 0x4d, 0xa4, 0x41, 0x3d, 0x16, 0x56, 0x82, 0x57, 0x68, 0xc6, 0x53, 0x29, 0xf7, 0xc8, 0xfe,
	0xbf, 0xde, 0xff, 0xa3, 0x36, 0x8b, 0xd8, 0x12, 0xf4, 0x75, 0x07, 0x1b, 0xa2, 0x32, 0x83, 0xd1,
	0x6a, 0x93, 0x26, 0x1f, 0x9b, 0xb4, 0x9d, 0x83, 0xbe, 0x3b, 0xeb, 0xfe, 0x46, 0x74, 0x5f, 0xde,
	0xd2, 0xde, 0x4c, 0xf9, 0xf9, 0x32, 0x63, 0x02, 0x75, 0x5c, 0x30, 0x3e, 0x87, 0x6e, 0x72, 0xcb,
	0x7d, 0xbe, 0x90, 0x2e, 0xd0, 0xdc, 0xf5, 0x4e, 0x00, 0x0c, 0xa3, 0xff, 0x5c, 0xca, 0xc1, 0xe5,
	0x6a, 0x4b, 0xc9, 0x7a, 0x4b, 0xc9, 0xfb, 0x96, 0x92, 0xc7, 0x82, 0x26, 0xeb, 0x82, 0x26, 0xaf,
	0x05, 0x4d, 0x6e, 0x4e, 0x6a, 0xd4, 0x0b, 0xa5, 0xe5, 0x30, 0x44, 0x57, 0x8f, 0xf1, 0xe1, 0x47,
	0x90, 0x61, 0x4e, 0xd6, 0x08, 0xa7, 0x1f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x8b, 0xd7,
	0x19, 0xd5, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomCreationFee) > 0 {
		for iNdEx := len(m.DenomCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DenomCreationFee) > 0 {
		for _, e := range m.DenomCreationFee {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomCreationFee = append(m.DenomCreationFee, types.Coin{})
			if err := m.DenomCreationFee[len(m.DenomCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
