// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mantrachain/token/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the token module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params            Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	NftCollectionList []NftCollection `protobuf:"bytes,2,rep,name=nft_collection_list,json=nftCollectionList,proto3" json:"nft_collection_list"`
	NftList           []Nft           `protobuf:"bytes,3,rep,name=nft_list,json=nftList,proto3" json:"nft_list"`
	// this line is used by starport scaffolding # genesis/proto/state
	SoulBondedNftsCollectionList [][]byte              `protobuf:"bytes,4,rep,name=soul_bonded_nfts_collection_list,json=soulBondedNftsCollectionList,proto3" json:"soul_bonded_nfts_collection_list,omitempty"`
	RestrictedNftsCollectionList [][]byte              `protobuf:"bytes,5,rep,name=restricted_nfts_collection_list,json=restrictedNftsCollectionList,proto3" json:"restricted_nfts_collection_list,omitempty"`
	OpenedNftsCollectionList     [][]byte              `protobuf:"bytes,6,rep,name=opened_nfts_collection_list,json=openedNftsCollectionList,proto3" json:"opened_nfts_collection_list,omitempty"`
	NftCollectionOwnerList       []*NftCollectionOwner `protobuf:"bytes,7,rep,name=nft_collection_owner_list,json=nftCollectionOwnerList,proto3" json:"nft_collection_owner_list,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d19a516f58e9c64, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetNftCollectionList() []NftCollection {
	if m != nil {
		return m.NftCollectionList
	}
	return nil
}

func (m *GenesisState) GetNftList() []Nft {
	if m != nil {
		return m.NftList
	}
	return nil
}

func (m *GenesisState) GetSoulBondedNftsCollectionList() [][]byte {
	if m != nil {
		return m.SoulBondedNftsCollectionList
	}
	return nil
}

func (m *GenesisState) GetRestrictedNftsCollectionList() [][]byte {
	if m != nil {
		return m.RestrictedNftsCollectionList
	}
	return nil
}

func (m *GenesisState) GetOpenedNftsCollectionList() [][]byte {
	if m != nil {
		return m.OpenedNftsCollectionList
	}
	return nil
}

func (m *GenesisState) GetNftCollectionOwnerList() []*NftCollectionOwner {
	if m != nil {
		return m.NftCollectionOwnerList
	}
	return nil
}

// NftCollectionOwner defines the nft collection owner.
type NftCollectionOwner struct {
	Index []byte `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Owner []byte `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *NftCollectionOwner) Reset()         { *m = NftCollectionOwner{} }
func (m *NftCollectionOwner) String() string { return proto.CompactTextString(m) }
func (*NftCollectionOwner) ProtoMessage()    {}
func (*NftCollectionOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d19a516f58e9c64, []int{1}
}
func (m *NftCollectionOwner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftCollectionOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftCollectionOwner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftCollectionOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftCollectionOwner.Merge(m, src)
}
func (m *NftCollectionOwner) XXX_Size() int {
	return m.Size()
}
func (m *NftCollectionOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_NftCollectionOwner.DiscardUnknown(m)
}

var xxx_messageInfo_NftCollectionOwner proto.InternalMessageInfo

func (m *NftCollectionOwner) GetIndex() []byte {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *NftCollectionOwner) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "mantrachain.token.v1.GenesisState")
	proto.RegisterType((*NftCollectionOwner)(nil), "mantrachain.token.v1.NftCollectionOwner")
}

func init() {
	proto.RegisterFile("mantrachain/token/v1/genesis.proto", fileDescriptor_9d19a516f58e9c64)
}

var fileDescriptor_9d19a516f58e9c64 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x40, 0xe3, 0x26, 0x4d, 0x61, 0x9b, 0x4b, 0x4d, 0x84, 0xdc, 0x50, 0xb9, 0x26, 0x5c, 0x0c,
	0x12, 0xb6, 0xda, 0xde, 0x90, 0x10, 0xd4, 0x88, 0x72, 0xa1, 0x01, 0x19, 0x2e, 0x70, 0xb1, 0x36,
	0xce, 0xda, 0x5d, 0x61, 0xcf, 0x5a, 0xde, 0x69, 0x29, 0x7f, 0xc1, 0x95, 0x3f, 0xe0, 0xc8, 0x67,
	0xf4, 0xd8, 0x23, 0x27, 0x84, 0x92, 0x03, 0xbf, 0x81, 0xbc, 0x6b, 0x41, 0x48, 0x6c, 0x89, 0x8b,
	0xb5, 0x3b, 0xfb, 0xe6, 0xcd, 0x78, 0x34, 0x64, 0x9c, 0x53, 0xc0, 0x92, 0xc6, 0x67, 0x94, 0x83,
	0x8f, 0xe2, 0x03, 0x03, 0xff, 0xe2, 0xc0, 0x4f, 0x19, 0x30, 0xc9, 0xa5, 0x57, 0x94, 0x02, 0x85,
	0x39, 0x5c, 0x62, 0x3c, 0xc5, 0x78, 0x17, 0x07, 0xa3, 0x1d, 0x9a, 0x73, 0x10, 0xbe, 0xfa, 0x6a,
	0x70, 0x34, 0x4c, 0x45, 0x2a, 0xd4, 0xd1, 0xaf, 0x4e, 0x75, 0xf4, 0x6e, 0x63, 0x89, 0x82, 0x96,
	0x34, 0xaf, 0x2b, 0x8c, 0xec, 0x46, 0x04, 0x12, 0xac, 0xdf, 0xef, 0xb7, 0xbd, 0x47, 0xb1, 0xc8,
	0x32, 0x16, 0x23, 0x17, 0xa0, 0xd1, 0xf1, 0x97, 0x1e, 0x19, 0xbc, 0xd0, 0xed, 0xbf, 0x41, 0x8a,
	0xcc, 0x7c, 0x42, 0xfa, 0xba, 0x96, 0x65, 0x38, 0x86, 0xbb, 0x7d, 0xb8, 0xe7, 0x35, 0xfd, 0x8e,
	0xf7, 0x5a, 0x31, 0xc1, 0xcd, 0xab, 0x1f, 0xfb, 0x9d, 0xaf, 0xbf, 0xbe, 0x3d, 0x30, 0xc2, 0x3a,
	0xcd, 0x7c, 0x47, 0x6e, 0xfd, 0x5b, 0x29, 0xca, 0xb8, 0x44, 0x6b, 0xc3, 0xe9, 0xba, 0xdb, 0x87,
	0xf7, 0x9a, 0x6d, 0x93, 0x04, 0x9f, 0xfd, 0xe1, 0x83, 0x5e, 0x25, 0x0d, 0x77, 0x60, 0x39, 0xf8,
	0x92, 0x4b, 0x34, 0x1f, 0x91, 0x1b, 0x95, 0x5a, 0xf9, 0xba, 0xca, 0xb7, 0xdb, 0xea, 0xab, 0x2d,
	0x5b, 0x90, 0xa0, 0xca, 0x3d, 0x21, 0x8e, 0x14, 0xe7, 0x59, 0x34, 0x15, 0x30, 0x63, 0xb3, 0x08,
	0x12, 0x94, 0x6b, 0x3d, 0xf6, 0x9c, 0xae, 0x3b, 0x08, 0xf7, 0x2a, 0x2e, 0x50, 0xd8, 0x24, 0x41,
	0xb9, 0xd2, 0xc3, 0x73, 0xb2, 0x5f, 0x32, 0x89, 0x25, 0x8f, 0xb1, 0x4d, 0xb3, 0xa9, 0x35, 0x7f,
	0xb1, 0x06, 0xcd, 0x63, 0x72, 0x47, 0x14, 0x0c, 0xda, 0x14, 0x7d, 0xa5, 0xb0, 0x34, 0xd2, 0x90,
	0x1e, 0x93, 0xdd, 0x95, 0x21, 0x8b, 0x8f, 0xc0, 0x4a, 0x9d, 0xbc, 0xa5, 0x46, 0xe3, 0xfe, 0xc7,
	0xa8, 0x5f, 0x55, 0x49, 0xe1, 0x6d, 0x58, 0x8b, 0x55, 0x45, 0xc6, 0x4f, 0x89, 0xb9, 0x4e, 0x9b,
	0x43, 0xb2, 0xc9, 0x61, 0xc6, 0x2e, 0xd5, 0x7e, 0x0c, 0x42, 0x7d, 0xa9, 0xa2, 0xaa, 0x03, 0x6b,
	0x43, 0x47, 0xd5, 0x25, 0x38, 0xbd, 0x9a, 0xdb, 0xc6, 0xf5, 0xdc, 0x36, 0x7e, 0xce, 0x6d, 0xe3,
	0xf3, 0xc2, 0xee, 0x5c, 0x2f, 0xec, 0xce, 0xf7, 0x85, 0xdd, 0x79, 0x7f, 0x94, 0x72, 0x3c, 0x3b,
	0x9f, 0x7a, 0xb1, 0xc8, 0xfd, 0xd3, 0xe3, 0xc9, 0xdb, 0xf0, 0xf8, 0xe1, 0x09, 0x07, 0x0a, 0x31,
	0xf3, 0x97, 0x97, 0xf7, 0xb2, 0x5e, 0x5f, 0xfc, 0x54, 0x30, 0x39, 0xed, 0xab, 0x9d, 0x3d, 0xfa,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xd9, 0x68, 0x61, 0x86, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftCollectionOwnerList) > 0 {
		for iNdEx := len(m.NftCollectionOwnerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftCollectionOwnerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.OpenedNftsCollectionList) > 0 {
		for iNdEx := len(m.OpenedNftsCollectionList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OpenedNftsCollectionList[iNdEx])
			copy(dAtA[i:], m.OpenedNftsCollectionList[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.OpenedNftsCollectionList[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RestrictedNftsCollectionList) > 0 {
		for iNdEx := len(m.RestrictedNftsCollectionList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RestrictedNftsCollectionList[iNdEx])
			copy(dAtA[i:], m.RestrictedNftsCollectionList[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RestrictedNftsCollectionList[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SoulBondedNftsCollectionList) > 0 {
		for iNdEx := len(m.SoulBondedNftsCollectionList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SoulBondedNftsCollectionList[iNdEx])
			copy(dAtA[i:], m.SoulBondedNftsCollectionList[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.SoulBondedNftsCollectionList[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.NftList) > 0 {
		for iNdEx := len(m.NftList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.NftCollectionList) > 0 {
		for iNdEx := len(m.NftCollectionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftCollectionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NftCollectionOwner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftCollectionOwner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftCollectionOwner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.NftCollectionList) > 0 {
		for _, e := range m.NftCollectionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NftList) > 0 {
		for _, e := range m.NftList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SoulBondedNftsCollectionList) > 0 {
		for _, b := range m.SoulBondedNftsCollectionList {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RestrictedNftsCollectionList) > 0 {
		for _, b := range m.RestrictedNftsCollectionList {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OpenedNftsCollectionList) > 0 {
		for _, b := range m.OpenedNftsCollectionList {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NftCollectionOwnerList) > 0 {
		for _, e := range m.NftCollectionOwnerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *NftCollectionOwner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftCollectionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftCollectionList = append(m.NftCollectionList, NftCollection{})
			if err := m.NftCollectionList[len(m.NftCollectionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftList = append(m.NftList, Nft{})
			if err := m.NftList[len(m.NftList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoulBondedNftsCollectionList", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SoulBondedNftsCollectionList = append(m.SoulBondedNftsCollectionList, make([]byte, postIndex-iNdEx))
			copy(m.SoulBondedNftsCollectionList[len(m.SoulBondedNftsCollectionList)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RestrictedNftsCollectionList", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RestrictedNftsCollectionList = append(m.RestrictedNftsCollectionList, make([]byte, postIndex-iNdEx))
			copy(m.RestrictedNftsCollectionList[len(m.RestrictedNftsCollectionList)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenedNftsCollectionList", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OpenedNftsCollectionList = append(m.OpenedNftsCollectionList, make([]byte, postIndex-iNdEx))
			copy(m.OpenedNftsCollectionList[len(m.OpenedNftsCollectionList)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftCollectionOwnerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftCollectionOwnerList = append(m.NftCollectionOwnerList, &NftCollectionOwner{})
			if err := m.NftCollectionOwnerList[len(m.NftCollectionOwnerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftCollectionOwner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftCollectionOwner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftCollectionOwner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = append(m.Index[:0], dAtA[iNdEx:postIndex]...)
			if m.Index == nil {
				m.Index = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
