// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aumega/rewards/v1beta1/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MaxClaimedRangeLength uint64                                 `protobuf:"varint,1,opt,name=max_claimed_range_length,json=maxClaimedRangeLength,proto3" json:"max_claimed_range_length,omitempty"`
	MinDepositTime        uint64                                 `protobuf:"varint,2,opt,name=min_deposit_time,json=minDepositTime,proto3" json:"min_deposit_time,omitempty"`
	DistributionPeriod    uint64                                 `protobuf:"varint,3,opt,name=distribution_period,json=distributionPeriod,proto3" json:"distribution_period,omitempty"`
	PairsCycleMaxCount    uint64                                 `protobuf:"varint,4,opt,name=pairs_cycle_max_count,json=pairsCycleMaxCount,proto3" json:"pairs_cycle_max_count,omitempty"`
	DistributionFeeRate   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=distribution_fee_rate,json=distributionFeeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"distribution_fee_rate"`
	MaxSnapshotsCount     uint64                                 `protobuf:"varint,6,opt,name=max_snapshots_count,json=maxSnapshotsCount,proto3" json:"max_snapshots_count,omitempty"`
	MaxPurgedRangeLength  uint64                                 `protobuf:"varint,7,opt,name=max_purged_range_length,json=maxPurgedRangeLength,proto3" json:"max_purged_range_length,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_279e871468a9e8ef, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxClaimedRangeLength() uint64 {
	if m != nil {
		return m.MaxClaimedRangeLength
	}
	return 0
}

func (m *Params) GetMinDepositTime() uint64 {
	if m != nil {
		return m.MinDepositTime
	}
	return 0
}

func (m *Params) GetDistributionPeriod() uint64 {
	if m != nil {
		return m.DistributionPeriod
	}
	return 0
}

func (m *Params) GetPairsCycleMaxCount() uint64 {
	if m != nil {
		return m.PairsCycleMaxCount
	}
	return 0
}

func (m *Params) GetMaxSnapshotsCount() uint64 {
	if m != nil {
		return m.MaxSnapshotsCount
	}
	return 0
}

func (m *Params) GetMaxPurgedRangeLength() uint64 {
	if m != nil {
		return m.MaxPurgedRangeLength
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "aumega.rewards.v1beta1.Params")
}

func init() {
	proto.RegisterFile("aumega/rewards/v1beta1/params.proto", fileDescriptor_279e871468a9e8ef)
}

var fileDescriptor_279e871468a9e8ef = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4f, 0x8b, 0xd4, 0x30,
	0x18, 0xc6, 0x5b, 0x77, 0x1c, 0x31, 0x07, 0xd1, 0xec, 0x8e, 0x16, 0x0f, 0x9d, 0x45, 0x41, 0xe6,
	0xb2, 0x0d, 0x83, 0x88, 0xe0, 0xcd, 0x9d, 0x45, 0x2f, 0x0a, 0x43, 0xf5, 0xe4, 0x25, 0xbc, 0x6d,
	0x5f, 0xdb, 0xe0, 0xe4, 0x0f, 0x49, 0xaa, 0xdd, 0x6f, 0xe1, 0xd1, 0xe3, 0x7e, 0x9c, 0x3d, 0xee,
	0x51, 0x3c, 0x2c, 0x32, 0xf3, 0x45, 0xa4, 0x69, 0x95, 0x59, 0x4f, 0x09, 0xf9, 0x3d, 0x0f, 0x79,
	0xde, 0x3f, 0xe4, 0x29, 0xb4, 0x12, 0x6b, 0x60, 0x16, 0xbf, 0x81, 0xad, 0x1c, 0xfb, 0xba, 0x2c,
	0xd0, 0xc3, 0x92, 0x19, 0xb0, 0x20, 0x5d, 0x66, 0xac, 0xf6, 0x9a, 0x3e, 0x1c, 0x44, 0xd9, 0x28,
	0xca, 0x46, 0xd1, 0xe3, 0xa3, 0x5a, 0xd7, 0x3a, 0x48, 0x58, 0x7f, 0x1b, 0xd4, 0x4f, 0x2e, 0x0e,
	0xc8, 0x74, 0x1d, 0xec, 0xf4, 0x25, 0x49, 0x24, 0x74, 0xbc, 0xdc, 0x80, 0x90, 0x58, 0x71, 0x0b,
	0xaa, 0x46, 0xbe, 0x41, 0x55, 0xfb, 0x26, 0x89, 0x8f, 0xe3, 0xc5, 0x24, 0x9f, 0x49, 0xe8, 0x56,
	0x03, 0xce, 0x7b, 0xfa, 0x2e, 0x40, 0xba, 0x20, 0xf7, 0xa5, 0x50, 0xbc, 0x42, 0xa3, 0x9d, 0xf0,
	0xdc, 0x0b, 0x89, 0xc9, 0xad, 0x60, 0xb8, 0x27, 0x85, 0x3a, 0x1b, 0x9e, 0x3f, 0x0a, 0x89, 0x94,
	0x91, 0xc3, 0x4a, 0x38, 0x6f, 0x45, 0xd1, 0x7a, 0xa1, 0x15, 0x37, 0x68, 0x85, 0xae, 0x92, 0x83,
	0x20, 0xa6, 0xfb, 0x68, 0x1d, 0x08, 0x5d, 0x92, 0x99, 0x01, 0x61, 0x1d, 0x2f, 0xcf, 0xcb, 0x0d,
	0xf2, 0x90, 0x4f, 0xb7, 0xca, 0x27, 0x93, 0xc1, 0x12, 0xe0, 0xaa, 0x67, 0xef, 0xa1, 0x5b, 0xf5,
	0x84, 0x16, 0x64, 0x76, 0xe3, 0x8f, 0xcf, 0x88, 0xdc, 0x82, 0xc7, 0xe4, 0xf6, 0x71, 0xbc, 0xb8,
	0x7b, 0x9a, 0x5d, 0x5e, 0xcf, 0xa3, 0x5f, 0xd7, 0xf3, 0x67, 0xb5, 0xf0, 0x4d, 0x5b, 0x64, 0xa5,
	0x96, 0xac, 0xd4, 0x4e, 0x6a, 0x37, 0x1e, 0x27, 0xae, 0xfa, 0xc2, 0xfc, 0xb9, 0x41, 0x97, 0x9d,
	0x61, 0x99, 0xdf, 0x08, 0xfc, 0x06, 0x31, 0x07, 0x8f, 0x34, 0x23, 0x87, 0x7d, 0x14, 0xa7, 0xc0,
	0xb8, 0x46, 0x7b, 0x37, 0x86, 0x9a, 0x86, 0x50, 0x0f, 0x24, 0x74, 0x1f, 0xfe, 0x92, 0x21, 0xd3,
	0x0b, 0xf2, 0xa8, 0xd7, 0x9b, 0xd6, 0xd6, 0xff, 0x77, 0xf6, 0x4e, 0xf0, 0x1c, 0x49, 0xe8, 0xd6,
	0x81, 0xee, 0x35, 0xf6, 0xd5, 0xe4, 0xc7, 0xc5, 0x3c, 0x3a, 0x7d, 0x7b, 0xb9, 0x4d, 0xe3, 0xab,
	0x6d, 0x1a, 0xff, 0xde, 0xa6, 0xf1, 0xf7, 0x5d, 0x1a, 0x5d, 0xed, 0xd2, 0xe8, 0xe7, 0x2e, 0x8d,
	0x3e, 0x9d, 0xec, 0xd5, 0xf0, 0x3a, 0x4c, 0x7d, 0xd5, 0x80, 0x50, 0x6c, 0x5c, 0x93, 0xee, 0xdf,
	0xa2, 0x84, 0x72, 0x8a, 0x69, 0x18, 0xf9, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x75,
	0x3f, 0x2c, 0x47, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxPurgedRangeLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPurgedRangeLength))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxSnapshotsCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSnapshotsCount))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.DistributionFeeRate.Size()
		i -= size
		if _, err := m.DistributionFeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.PairsCycleMaxCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PairsCycleMaxCount))
		i--
		dAtA[i] = 0x20
	}
	if m.DistributionPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DistributionPeriod))
		i--
		dAtA[i] = 0x18
	}
	if m.MinDepositTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDepositTime))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxClaimedRangeLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxClaimedRangeLength))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxClaimedRangeLength != 0 {
		n += 1 + sovParams(uint64(m.MaxClaimedRangeLength))
	}
	if m.MinDepositTime != 0 {
		n += 1 + sovParams(uint64(m.MinDepositTime))
	}
	if m.DistributionPeriod != 0 {
		n += 1 + sovParams(uint64(m.DistributionPeriod))
	}
	if m.PairsCycleMaxCount != 0 {
		n += 1 + sovParams(uint64(m.PairsCycleMaxCount))
	}
	l = m.DistributionFeeRate.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxSnapshotsCount != 0 {
		n += 1 + sovParams(uint64(m.MaxSnapshotsCount))
	}
	if m.MaxPurgedRangeLength != 0 {
		n += 1 + sovParams(uint64(m.MaxPurgedRangeLength))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClaimedRangeLength", wireType)
			}
			m.MaxClaimedRangeLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClaimedRangeLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDepositTime", wireType)
			}
			m.MinDepositTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDepositTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionPeriod", wireType)
			}
			m.DistributionPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairsCycleMaxCount", wireType)
			}
			m.PairsCycleMaxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PairsCycleMaxCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DistributionFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSnapshotsCount", wireType)
			}
			m.MaxSnapshotsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSnapshotsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPurgedRangeLength", wireType)
			}
			m.MaxPurgedRangeLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPurgedRangeLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
