on:
  push:
    branches: main
  pull_request:
    branches: main

name: Run govulncheck
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
          check-latest: true
